import {buildReport,createOccurrence,extractTextFromHtml,parseBookmarkHtml,sha256,toCsv} from "./engine.mjs";
import {clearState,readState,writeState} from "./storage.mjs";
import {FUNCTION_REGISTRY,createJob,transitionJob} from "./jobs.mjs";
import {POVS,applyPov} from "./pov.mjs";
import {collectSubmission} from "./collection.mjs";
import {saveContact} from "./contact.mjs";

const $=s=>document.querySelector(s),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const selected=[];let povId=await readState("drain-lite-pov","BLENDED"),items=await readState("drain-lite-items",[]),receipt=await readState("drain-lite-receipt",null),jobs=await readState("drain-lite-jobs",[]),settings=await readState("drain-lite-settings",{collectionEnabled:true}),activeJob=null,cancelled=false,activeBucket="ALL";
const sessionId=await readState("drain-lite-session",null)||crypto.randomUUID().replaceAll("-","").slice(0,32);
await writeState("drain-lite-session",sessionId);
$("#pov").innerHTML=POVS.map(x=>`<option value="${x.id}">${x.label}</option>`).join("");$("#pov").value=povId;$("#pov").onchange=async()=>{povId=$("#pov").value;await writeState("drain-lite-pov",povId);renderPovNote();render()};renderPovNote();$("#function").innerHTML=FUNCTION_REGISTRY.map(x=>`<option value="${x.id}">${x.name} · ${x.status}</option>`).join("");
const tabs=["intake","dashboard","report","registry","controller","settings"];$("#tabs").innerHTML=tabs.map(x=>`<button data-tab="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join("");
function tab(name){tabs.forEach(x=>$("#"+x).classList.toggle("hidden",x!==name));document.querySelectorAll("#tabs button").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));if(name!=="intake")render();if(name==="controller")renderController();if(name==="settings")renderSettings()}
document.querySelectorAll("#tabs button").forEach(x=>x.onclick=()=>tab(x.dataset.tab));
const setState=s=>{$("#state").textContent=s;if(!activeJob)return;if(/analysed/.test(s)){receipt={...receipt,job_id:activeJob.job_id,function_id:activeJob.function_id,priority:activeJob.priority};activeJob=transitionJob(activeJob,cancelled?"cancelled":"succeeded",{receiptRef:receipt?.evidence_hash?`receipt:${receipt.evidence_hash}`:null});jobs[jobs.length-1]=activeJob;void Promise.all([writeState("drain-lite-receipt",receipt),writeState("drain-lite-jobs",jobs)])}else if(s==="Blocked"&&activeJob.status==="running"){activeJob=transitionJob(activeJob,"failed",{error:"intake_execution_failed"});jobs[jobs.length-1]=activeJob;void writeState("drain-lite-jobs",jobs)}};
function renderSelection(){$("#selection").innerHTML=selected.length?`<h2>${selected.length} selected</h2>${selected.map(f=>`<div>${esc(f.webkitRelativePath||f.name)} <small>${(f.size/1024).toFixed(1)} KB</small></div>`).join("")}`:"<p>No files selected.</p>";$("#run").disabled=!selected.length}
function renderSettings(){const saveContactButton=$("#saveContact");if(saveContactButton)saveContactButton.onclick=async()=>{const email=$("#contactEmail").value.trim();const marketingConsent=$("#marketingConsent").checked;$("#contactStatus").textContent="Saving...";const result=await saveContact({email,marketingConsent,sessionId});$("#contactStatus").textContent=result.status==="SAVED"?"Saved. Thank you.":result.status==="BLOCKED"?"Please check the email address and try again.":"Not saved.";};$("#collectionEnabled").checked=settings.collectionEnabled!==false;$("#collectionEnabled").onchange=async()=>{settings.collectionEnabled=$("#collectionEnabled").checked;await writeState("drain-lite-settings",settings);renderCollectionNotice()};$("#deleteLocalData").onclick=async()=>{if(!confirm("Delete all drAIn Lite data stored in this browser?"))return;items=[];receipt=null;jobs=[];selected.length=0;await clearState();await writeState("drain-lite-settings",settings);await writeState("drain-lite-session",sessionId);renderSelection();renderCollectionNotice();tab("intake")};renderCollectionNotice()}
function renderPovNote(){const p=POVS.find(x=>x.id===povId)||POVS[0];$("#povNote").innerHTML=`<b>${esc(p.label)} view.</b> ${esc(p.description)} The same recovered evidence is used; this view changes prioritisation, not the source material.`}function renderCollectionNotice(){const on=settings.collectionEnabled!==false;$("#collectionNotice").innerHTML=on?`<b>Use data to improve the model is ON.</b> drAIn Lite sends derived signals such as counts, hashes, source types and scores to help improve the product. Raw source material is not collected by this setting. <button id="turnCollectionOff">Turn it off</button>.`:`<b>Product improvement collection is OFF.</b> Your analysis stays in this browser. <button id="turnCollectionOn">Turn it on</button>.`;$("#turnCollectionOff")?.addEventListener("click",async()=>{settings.collectionEnabled=false;await writeState("drain-lite-settings",settings);renderCollectionNotice();renderSettings()});$("#turnCollectionOn")?.addEventListener("click",async()=>{settings.collectionEnabled=true;await writeState("drain-lite-settings",settings);renderCollectionNotice();renderSettings()})}
function addFiles(files){for(const f of files)selected.push(f);renderSelection()}$("#choose").onclick=()=>$("#files").click();$("#files").onchange=e=>addFiles(e.target.files);$("#clear").onclick=()=>{selected.length=0;$("#files").value="";renderSelection()};
const drop=$("#drop");["dragenter","dragover"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add("over")}));["dragleave","drop"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove("over")}));drop.addEventListener("drop",e=>addFiles(e.dataTransfer.files));
$("#run").addEventListener("click",event=>{activeJob=createJob({functionId:$("#function").value,priority:$("#priority").value,context:$("#context").value,files:selected});jobs.push(activeJob);if(activeJob.function_id!=="FN-SUPER-DRAIN-ANALYSER"){event.preventDefault();event.stopImmediatePropagation();setState("Queued");$("#progress").classList.remove("hidden");$("#progress").innerHTML=`<h2>Job queued</h2><p>${activeJob.job_id}</p><p>${activeJob.function_id} requires its governed worker connection.</p>`;void writeState("drain-lite-jobs",jobs);return}activeJob=transitionJob(activeJob,"running");jobs[jobs.length-1]=activeJob;void writeState("drain-lite-jobs",jobs)},{capture:true});
const textTypes=new Set(["html","htm","txt","md","markdown","csv","tsv","json","jsonl","ndjson","sql","py","js","mjs","cjs","ts","tsx","jsx","css","yaml","yml","toml","xml","svg","sh","command","log","ini","env"]);
async function packed(name,bytes,type){const binary=!textTypes.has(type);return{name,type,binary,size:bytes.length,asset_hash:await sha256(bytes),text:binary?"":new TextDecoder().decode(bytes)}}
async function expand(files){const out=[];for(const file of files){const type=file.name.split(".").pop().toLowerCase();if(type==="zip"){if(!window.JSZip)throw new Error("ZIP support could not load. Extract the ZIP and drop the folder.");const zip=await JSZip.loadAsync(file);for(const [name,entry] of Object.entries(zip.files))if(!entry.dir)out.push(await packed(`${file.name}/${name}`,await entry.async("uint8array"),name.split(".").pop().toLowerCase()))}else out.push(await packed(file.webkitRelativePath||file.name,new Uint8Array(await file.arrayBuffer()),type))}return out}
function rawOccurrences(file){if(file.binary)return[{source_file:file.name,source_type:"binary_asset",occurrence_ref:`${file.name}:asset-1`,title:file.name,content:`Preserved binary asset. Bytes: ${file.size}. SHA-256 evidence: ${file.asset_hash}`}];if(/html?|htm/.test(file.type)){const bookmarks=parseBookmarkHtml(file.text,file.name);if(bookmarks.length)return bookmarks.map(x=>({...x,source_file:file.name}));return[{source_file:file.name,source_type:"html_page",occurrence_ref:`${file.name}:page-1`,title:file.name,content:extractTextFromHtml(file.text)}]}if(file.type==="json"){try{const value=JSON.parse(file.text),rows=Array.isArray(value)?value:[value];return rows.map((x,i)=>({source_file:file.name,source_type:"json_record",occurrence_ref:`${file.name}:record-${i+1}`,title:x.title||x.name||file.name,url:x.url||"",content:JSON.stringify(x)}))}catch{}}const code=["py","js","mjs","cjs","ts","tsx","jsx","sql","sh","command"].includes(file.type);if(code)return[{source_file:file.name,source_type:`${file.type}_code_asset`,occurrence_ref:`${file.name}:code-1`,title:file.name,url:"",content:file.text}];return[{source_file:file.name,source_type:"text_source",occurrence_ref:`${file.name}:source-1`,title:file.name,url:"",content:file.text}]}
$("#run").onclick=async()=>{cancelled=false;$("#run").disabled=true;setState("Ingesting");try{const files=await expand(selected),raws=files.flatMap(rawOccurrences),batch={batch_id:`batch_${Date.now()}`,source_name:selected.map(x=>x.name).join(", "),source_type:"bulk_file",started_at:new Date().toISOString()},corpus=new Set(items.flatMap(x=>(x.title+" "+x.content).toLowerCase().match(/[a-z0-9]{5,}/g)||[])),existingHashes=new Set(items.map(x=>x.content_hash).filter(Boolean)),batchHashes=new Set(),next=[],duplicatesSkipped=[];$("#progress").classList.remove("hidden");for(let i=0;i<raws.length;i++){if(cancelled)break;const x=await createOccurrence(raws[i],batch,i,corpus);if(existingHashes.has(x.content_hash)||batchHashes.has(x.content_hash)){duplicatesSkipped.push({source_file:x.source_file,title:x.title,content_hash:x.content_hash});continue;}batchHashes.add(x.content_hash);x.control={mode:x.analysis.unfinished.length?"CHECKPOINT":"REGISTER",importance:x.analysis.scores.total>=65?"STRATEGIC":"OPERATIONAL",evidence:"",receipt_ref:"",bridge_id:batch.batch_id,target_ref:x.source_file,status:"PARTIAL"};next.push(x);if(i%25===0){$("#progress").innerHTML=`<h2>Processing ${i+1} of ${raws.length}</h2><div class="bar"><i style="width:${(i+1)/raws.length*100}%"></i></div><button id="cancel">Cancel safely</button>`;$("#cancel").onclick=()=>cancelled=true;await new Promise(r=>setTimeout(r,0))}}items.push(...next);await writeState("drain-lite-items",items);const report=buildReport(applyPov(next,povId),povId);receipt={schema:"t4h.drain-lite.receipt.v2.2",batch:{...batch,finished_at:new Date().toISOString(),selected_files:selected.length,expanded_files:files.length,occurrences_created:next.length,duplicates_skipped:duplicatesSkipped.length,cancelled},report,evidence_hash:await sha256(JSON.stringify({batch,ids:next.map(x=>x.occurrence_id),hashes:next.map(x=>x.content_hash)})),status:cancelled?"PARTIAL":"REAL"};await writeState("drain-lite-receipt",receipt);
if(settings.collectionEnabled!==false){const collection=await collectSubmission({collection_consent:true,session_id:sessionId,batch_id:batch.batch_id,source_type:batch.source_type,source_name:batch.source_name,context:"",items:next,receipt,content_hash:receipt.evidence_hash,app_version:"1.3.0",pov:povId});receipt.collection_status=collection.status;receipt.collection_receipt=collection.receipt||null;await writeState("drain-lite-receipt",receipt)}
selected.length=0;$("#files").value="";renderSelection();setState(`${next.length} analysed${duplicatesSkipped.length?` · ${duplicatesSkipped.length} duplicate${duplicatesSkipped.length===1?"":"s"} skipped`:""}`);tab("report")}catch(e){setState("Blocked");$("#progress").innerHTML=`<p class="error">${esc(e.message)}</p>`;$("#run").disabled=false}};
function list(id,values){$(id).innerHTML=values?.length?values.map((x,i)=>`<div class="finding"><b>${i+1}. ${esc(typeof x==="string"?x:x.value||x.title)}</b>${typeof x==="object"?`<small>${esc(x.page_id||"")} ${x.score!=null?" · score "+x.score:""}</small>`:""}</div>`).join(""):"<p>No evidence found yet.</p>"}
function render(){const r=buildReport(applyPov(items,povId),povId);$("#metrics").innerHTML=[["Sources",r.sources],["Evidence units",r.evidence_units],["Ideas",items.reduce((n,x)=>n+x.analysis.ideas.length,0)],["Actions",items.reduce((n,x)=>n+x.analysis.actions.length,0)],["Unfinished",items.reduce((n,x)=>n+x.analysis.unfinished.length,0)],["Opportunities",items.reduce((n,x)=>n+x.analysis.opportunities.length,0)]].map(([n,v])=>`<div class="metric"><b>${v}</b><span>${n} measured</span></div>`).join("");list("#found",r.top_actions);list("#topPages",r.top_pages);$("#novel").innerHTML=`<p><b>${r.known_vs_novel.known}</b> known signals · <b>${r.known_vs_novel.novel}</b> novel signals</p><p>Measures and guides for review, not claims of fact.</p>`;list("#opportunities",r.top_opportunities);list("#unfinished",r.top_unfinished);list("#nextActions",r.top_actions);list("#costs",r.top_opportunity_costs);list("#intendedOutputs",r.intended_outputs);list("#claims",r.completion_claims);$("#scopes").innerHTML=Object.entries(r.scope_measures).map(([scope,v])=>`<div class="finding"><b>${scope}</b><small>${Object.entries(v).map(([k,n])=>`${k.replaceAll("_"," ")}: ${n}`).join(" · ")}</small></div>`).join("");renderRows()}
function renderRows(){const q=$("#search").value.toLowerCase();$("#rows").innerHTML=items.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).slice().reverse().slice(0,500).map(x=>`<tr><td>${x.page_id}</td><td>${x.occurrence_number}<small>${esc(x.source_file)}</small></td><td><b>${esc(x.title)}</b><small>${esc(x.url)}</small></td><td>${x.analysis.ideas.length} ideas · ${x.analysis.actions.length} actions · ${x.analysis.unfinished.length} gaps · ${x.analysis.intended_outputs.length} outputs</td><td><b>${x.analysis.scores.total}</b></td></tr>`).join("")}
const MODES=["ALL","BLOCKED","KILL","CHECKPOINT","HANDOFF","ARCHIVE","REGISTER","LIBRARY"],evidenceRx=/^(commit|receipt|issue|file|notion|pr):\S+/;
function violations(x){const c=x.control||{},v=[];if(c.mode==="ARCHIVE"&&(c.status!=="REAL"||!evidenceRx.test(c.evidence||"")))v.push("V1 ARCHIVE requires REAL and typed evidence");if(c.mode==="KILL"&&["IP","STRATEGIC"].includes(c.importance))v.push("V2 KILL blocked for IP/STRATEGIC");if(c.mode==="HANDOFF"&&!c.receipt_ref)v.push("V3 HANDOFF requires receipt");if(["IP","STRATEGIC"].includes(c.importance)&&!evidenceRx.test(c.evidence||""))v.push("V4 important work requires typed evidence");if(c.mode==="HANDOFF"&&!c.bridge_id)v.push("V5 HANDOFF requires bridge_id");if(c.mode==="REGISTER"&&!c.target_ref)v.push("V6 REGISTER requires target_ref");return v}
function derive(x){const c=x.control;if(!c)return;const v=violations(x);if(v.some(s=>/^V[12]/.test(s)))c.status="BLOCKED";else if(c.mode==="HANDOFF"&&c.receipt_ref&&evidenceRx.test(c.evidence||""))c.status="REAL";else if(["CHECKPOINT","LIBRARY"].includes(c.mode)&&evidenceRx.test(c.evidence||""))c.status="REAL";else if(c.mode==="KILL"&&!v.length)c.status="REAL";else c.status="PARTIAL"}
function renderController(){items.forEach(derive);const blocked=items.filter(x=>violations(x).length),debt=items.length?items.filter(x=>x.control?.status!=="REAL").length/items.length:0;$("#gate").textContent=blocked.length?"GATE CLOSED":"GATE OPEN";$("#controllerMetrics").innerHTML=[["Work units",items.length],["REAL",items.filter(x=>x.control?.status==="REAL").length],["Blocked",blocked.length],["Evidence debt",Math.round(debt*100)+"%"],["Target","<15%"]].map(([n,v])=>`<div class="metric"><b>${v}</b><span>${n}</span></div>`).join("");$("#buckets").innerHTML=MODES.map(m=>`<button class="${activeBucket===m?"primary":""}" data-mode="${m}">${m} (${m==="ALL"?items.length:m==="BLOCKED"?blocked.length:items.filter(x=>x.control?.mode===m).length})</button>`).join("");$("#buckets").querySelectorAll("button").forEach(b=>b.onclick=()=>{activeBucket=b.dataset.mode;renderController()});const visible=items.filter(x=>activeBucket==="ALL"||activeBucket==="BLOCKED"?activeBucket==="ALL"||violations(x).length:x.control?.mode===activeBucket);$("#controlled").innerHTML=visible.slice().reverse().slice(0,300).map(x=>{const c=x.control||{},v=violations(x);return`<article class="panel"><b>${esc(x.title)}</b><small>${x.page_id} · ${c.status}</small><div class="grid"><select data-id="${x.page_id}" data-field="mode">${MODES.slice(2).map(m=>`<option ${c.mode===m?"selected":""}>${m}</option>`).join("")}</select><select data-id="${x.page_id}" data-field="importance">${["OPERATIONAL","REFERENCE","STRATEGIC","IP"].map(m=>`<option ${c.importance===m?"selected":""}>${m}</option>`).join("")}</select><input data-id="${x.page_id}" data-field="target_ref" value="${esc(c.target_ref)}" placeholder="target_ref"><input data-id="${x.page_id}" data-field="evidence" value="${esc(c.evidence)}" placeholder="commit:sha or file:path"><input data-id="${x.page_id}" data-field="receipt_ref" value="${esc(c.receipt_ref)}" placeholder="receipt_ref"><input data-id="${x.page_id}" data-field="bridge_id" value="${esc(c.bridge_id)}" placeholder="bridge_id"></div>${v.length?`<p class="error">${v.join(" · ")}</p>`:""}</article>`}).join("")||"<div class='panel'>No work units.</div>";$("#controlled").querySelectorAll("input,select").forEach(el=>el.onchange=async()=>{const x=items.find(i=>i.page_id===el.dataset.id);x.control[el.dataset.field]=el.value;derive(x);await writeState("drain-lite-items",items);renderController()})}
$("#search").oninput=renderRows;$("#newBatch").onclick=()=>tab("intake");$("#flush").onclick=async()=>{if(confirm("Remove this local batch? Download its receipt first.")){items=[];receipt=null;await clearState();await writeState("drain-lite-settings",settings);await writeState("drain-lite-session",sessionId);setState("Flushed");tab("intake")}};
function download(name,type,data){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$("#json").onclick=()=>download("drain-lite-receipt.json","application/json",JSON.stringify(receipt||{report:buildReport(applyPov(items,povId),povId)},null,2));$("#csv").onclick=()=>download("drain-lite-workbook.csv","text/csv",toCsv(applyPov(items,povId),povId));
renderSelection();renderSettings();tab(items.length?"dashboard":"intake");