import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import {inferIntelligence} from "./intelligence.mjs";
export const hash=value=>crypto.createHash("sha256").update(Buffer.isBuffer(value)?value:typeof value==="string"?value:JSON.stringify(value)).digest("hex");
const now=()=>new Date().toISOString();
function atomicJson(target,value){fs.mkdirSync(path.dirname(target),{recursive:true});const temp=`${target}.${process.pid}.tmp`;fs.writeFileSync(temp,`${JSON.stringify(value,null,2)}\n`);fs.renameSync(temp,target)}
export class DrainStore{
 constructor(root){this.root=path.resolve(root);this.statePath=path.join(this.root,"state.json");this.receiptDir=path.join(this.root,"receipts");fs.mkdirSync(this.receiptDir,{recursive:true});if(!fs.existsSync(this.statePath))atomicJson(this.statePath,{schema:"t4h.super-drain.state.v1",items:[],work:[],events:[],sessions:[],updated_at:now()})}
 read(){return JSON.parse(fs.readFileSync(this.statePath,"utf8"))}
 write(state){state.updated_at=now();atomicJson(this.statePath,state)}
 receipt(kind,subject,payload){const base={kind,subject,payload,recorded_at:now()},evidence_hash=hash(JSON.stringify(base)),receipt_id=`rcpt_${evidence_hash.slice(0,24)}`,body={schema:"t4h.super-drain.receipt.v1",receipt_id,...base,evidence_hash},target=path.join(this.receiptDir,`${receipt_id}.json`);if(!fs.existsSync(target))atomicJson(target,body);const bytes=fs.readFileSync(target);return {...body,receipt_path:target,readback_hash:hash(bytes),readback_verified:JSON.parse(bytes).evidence_hash===evidence_hash}}
 event(state,eventKey,eventType,subject,payload){const existing=state.events.find(event=>event.event_key===eventKey);if(existing)return{event:existing,replayed:true};const event={event_id:`evt_${hash(eventKey).slice(0,24)}`,event_key:eventKey,event_type:eventType,subject,payload,created_at:now()};state.events.push(event);return{event,replayed:false}}
 ingest(input){const state=this.read(),sourceSystem=input.source_system||"manual",sourceSession=input.source_session||`session-${new Date().toISOString().slice(0,10)}`,sessionId=`ses_${hash(`${sourceSystem}:${sourceSession}`).slice(0,20)}`;if(!state.sessions.some(s=>s.session_id===sessionId))state.sessions.push({session_id:sessionId,source_system:sourceSystem,source_session:sourceSession,created_at:now()});const accepted=[],replayed=[];for(const[index,raw]of(input.items||[]).entries()){if(!raw.url&&!raw.content&&!raw.title)continue;const contentHash=hash(JSON.stringify({title:raw.title||"",url:raw.url||"",content:raw.content||""})),occurrenceRef=raw.occurrence_ref||`${sourceSession}:${index}`,idempotencyKey=hash(`${sourceSystem}:${sourceSession}:${occurrenceRef}:${contentHash}`),existing=state.items.find(item=>item.idempotency_key===idempotencyKey);if(existing){replayed.push(existing.occurrence_id);continue}const occurrenceId=`occ_${idempotencyKey.slice(0,24)}`,item={occurrence_id:occurrenceId,idempotency_key:idempotencyKey,content_hash:contentHash,source_system:sourceSystem,source_session:sourceSession,source_occurrence_ref:occurrenceRef,captured_at:now(),title:raw.title||raw.url||"Untitled occurrence",url:raw.url||"",content:raw.content||"",disposition:raw.disposition||"REVIEW",state:"RAW",intelligence:raw.intelligence||inferIntelligence({...raw,occurrence_ref:occurrenceRef}),scores:{signal:Number(raw.scores?.signal||0),reuse:Number(raw.scores?.reuse||0),monetisation:Number(raw.scores?.monetisation||0),urgency:Number(raw.scores?.urgency||0),completion_gap:Number(raw.scores?.completion_gap||0)}};state.items.push(item);this.event(state,`captured:${occurrenceId}`,"drain.item.captured",occurrenceId,{source_system:sourceSystem,source_session:sourceSession,content_hash:contentHash});accepted.push(occurrenceId)}const receipt=this.receipt("drain_intake",sessionId,{accepted,replayed,source_system:sourceSystem,source_session:sourceSession});this.write(state);return{status:"ACKED",session_id:sessionId,accepted,replayed,receipt}}
 autoAdvance(){const state=this.read(),results=[];for(const item of state.items){if(!["RAW","TRIAGE"].includes(item.state))continue;const disposition=String(item.disposition||"REVIEW").toUpperCase();if(["REGISTER","REVIEW","EXECUTE"].includes(disposition)){item.state="REGISTERED";const workId=`work_${item.idempotency_key.slice(0,24)}`;if(!state.work.some(work=>work.work_id===workId))state.work.push({work_id:workId,occurrence_id:item.occurrence_id,idempotency_key:item.idempotency_key,state:"READY",queue:"t4h.super-drain.ready",owner_principal:"principal:super-drain",created_at:now()});item.work_id=workId;item.state="DEV_ROUTED";const receipt=this.receipt("pen_super_drain_transfer",workId,{occurrence_id:item.occurrence_id,content_hash:item.content_hash,queue:"t4h.super-drain.ready"});item.receipt_id=receipt.receipt_id;this.event(state,`routed:${item.occurrence_id}`,"drain.item.dev_routed",workId,receipt);results.push({occurrence_id:item.occurrence_id,state:item.state,work_id:workId,receipt_id:receipt.receipt_id})}else if(disposition==="LIBRARY"){item.state="KNOWLEDGESET";const receipt=this.receipt("knowledge_registration",item.occurrence_id,{content_hash:item.content_hash});item.receipt_id=receipt.receipt_id;this.event(state,`library:${item.occurrence_id}`,"drain.item.knowledge_registered",item.occurrence_id,receipt);results.push({occurrence_id:item.occurrence_id,state:item.state,receipt_id:receipt.receipt_id})}else if(["KILL","QUARANTINE"].includes(disposition)){item.state="QUARANTINED";const receipt=this.receipt("drain_quarantine",item.occurrence_id,{reason:"explicit disposition"});item.receipt_id=receipt.receipt_id;this.event(state,`quarantine:${item.occurrence_id}`,"drain.item.quarantined",item.occurrence_id,receipt);results.push({occurrence_id:item.occurrence_id,state:item.state,receipt_id:receipt.receipt_id})}else{item.state="ARCHIVED";const receipt=this.receipt("drain_archive",item.occurrence_id,{content_hash:item.content_hash});item.receipt_id=receipt.receipt_id;this.event(state,`archive:${item.occurrence_id}`,"drain.item.archived",item.occurrence_id,receipt);results.push({occurrence_id:item.occurrence_id,state:item.state,receipt_id:receipt.receipt_id})}}const runReceipt=this.receipt("drain_auto_advance",`run_${hash(JSON.stringify(results)).slice(0,20)}`,{advanced:results.length,results});this.write(state);return{status:"SUCCEEDED",advanced:results.length,results,receipt:runReceipt}}
 snapshot(){const state=this.read(),countBy=(list,key)=>list.reduce((out,item)=>(out[item[key]]=(out[item[key]]||0)+1,out),{}),snapshot={status:"PARTIAL",items:state.items.length,work:state.work.length,events:state.events.length,sessions:state.sessions.length,item_states:countBy(state.items,"state"),dispositions:countBy(state.items,"disposition"),queue_states:countBy(state.work,"state"),updated_at:state.updated_at};snapshot.ledger_hash=hash(JSON.stringify(snapshot));return snapshot}
}
